'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CompletedTimePeriodResults

    '''<summary>
    '''TeamsByGameTable1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TeamsByGameTable1 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''Nothing1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber3 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber4 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber5 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber6 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber7 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber8 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber9 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber10 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber11 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber12 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber13 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber14 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber15 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber16 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Status1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber1Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber1Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber2Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber2Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber3Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber3Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber4Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber4Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber5Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber5Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber6Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber6Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber7Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber7Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber8Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber8Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber9Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber9Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber10Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber10Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber11Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber11Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber12Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber12Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber13Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber13Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber14Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber14Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber15Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber15Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber16Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber16Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Nothing1A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing1A As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam1Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam1Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam1Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam1Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam1Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam1Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam1Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam1Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam2Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam2Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam2Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam2Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam2Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam2Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam2Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam2Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam3Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam3Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam3Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam3Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam3Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam3Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam3Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam3Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam4Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam4Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam4Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam4Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam4Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam4Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam4Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam4Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam5Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam5Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam5Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam5Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam5Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam5Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam5Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam5Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam6Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam6Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam6Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam6Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam6Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam6Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam6Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam6Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam7Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam7Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam7Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam7Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam7Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam7Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam7Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam7Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam8Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam8Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam8Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam8Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam8Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam8Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam8Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam8Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam9Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam9Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam9Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam9Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam9Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam9Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam9Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam9Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam10Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam10Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam10Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam10Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam10Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam10Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam10Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam10Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam11Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam11Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam11Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam11Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam11Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam11Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam11Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam11Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam12Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam12Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam12Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam12Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam12Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam12Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam12Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam12Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam13Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam13Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam13Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam13Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam13Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam13Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam13Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam13Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam14Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam14Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam14Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam14Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam14Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam14Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam14Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam14Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam15Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam15Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam15Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam15Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam15Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam15Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam15Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam15Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam16Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam16Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam16Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam16Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam16Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam16Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam16Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam16Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Nothing1C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing1C As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam1Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam1Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam1Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam1Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam1Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam1Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam1Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam1Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam2Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam2Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam2Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam2Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam2Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam2Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam2Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam2Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam3Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam3Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam3Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam3Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam3Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam3Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam3Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam3Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam4Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam4Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam4Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam4Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam4Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam4Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam4Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam4Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam5Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam5Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam5Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam5Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam5Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam5Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam5Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam5Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam6Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam6Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam6Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam6Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam6Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam6Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam6Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam6Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam7Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam7Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam7Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam7Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam7Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam7Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam7Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam7Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam8Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam8Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam8Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam8Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam8Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam8Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam8Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam8Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam9Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam9Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam9Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam9Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam9Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam9Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam9Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam9Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam10Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam10Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam10Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam10Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam10Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam10Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam10Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam10Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam11Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam11Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam11Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam11Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam11Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam11Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam11Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam11Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam12Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam12Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam12Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam12Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam12Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam12Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam12Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam12Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam13Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam13Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam13Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam13Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam13Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam13Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam13Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam13Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam14Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam14Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam14Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam14Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam14Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam14Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam14Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam14Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam15Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam15Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam15Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam15Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam15Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam15Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam15Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam15Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam16Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam16Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam16Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam16Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam16Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam16Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam16Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam16Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Nothing1B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing1B As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore1 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore1 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore2 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore2 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore3 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore3 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore4 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore4 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore5 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore5 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore6 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore6 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore7 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore7 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore8 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore8 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore9 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore9 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore10 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore10 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore11 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore11 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore12 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore12 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore13 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore13 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore14 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore14 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore15 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore15 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore16 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore16 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Contenders4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Contenders4 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''ContendersName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContendersName As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team1Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team1Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team1Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team1Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team2Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team2Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team2Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team2Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team3Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team3Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team3Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team3Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team4Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team4Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team4Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team4Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team5Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team5Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team5Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team5Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team6Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team6Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team6Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team6Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team7Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team7Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team7Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team7Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team8Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team8Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team8Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team8Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team9Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team9Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team9Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team9Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team10Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team10Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team10Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team10Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team11Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team11Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team11Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team11Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team12Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team12Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team12Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team12Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team13Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team13Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team13Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team13Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team14Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team14Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team14Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team14Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team15Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team15Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team15Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team15Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team16Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team16Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team16Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team16Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team17Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team17Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team17Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team17Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team18Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team18Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team18Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team18Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team19Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team19Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team19Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team19Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team20Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team20Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team20Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team20Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team21Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team21Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team21Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team21Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team22Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team22Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team22Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team22Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team23Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team23Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team23Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team23Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team24Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team24Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team24Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team24Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team25Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team25Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team25Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team25Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team26Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team26Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team26Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team26Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team27Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team27Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team27Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team27Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team28Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team28Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team28Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team28Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team29Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team29Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team29Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team29Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team30Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team30Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team30Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team30Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team31Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team31Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team31Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team31Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team32Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team32Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team32Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team32Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ContendersName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContendersName1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team1Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team1Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team1Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team1Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team2Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team2Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team2Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team2Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team3Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team3Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team3Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team3Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team4Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team4Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team4Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team4Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team5Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team5Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team5Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team5Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team6Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team6Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team6Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team6Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team7Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team7Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team7Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team7Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team8Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team8Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team8Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team8Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team9Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team9Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team9Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team9Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team10Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team10Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team10Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team10Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team11Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team11Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team11Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team11Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team12Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team12Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team12Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team12Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team13Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team13Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team13Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team13Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team14Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team14Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team14Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team14Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team15Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team15Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team15Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team15Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team16Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team16Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team16Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team16Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team17Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team17Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team17Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team17Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team18Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team18Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team18Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team18Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team19Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team19Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team19Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team19Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team20Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team20Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team20Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team20Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team21Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team21Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team21Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team21Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team22Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team22Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team22Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team22Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team23Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team23Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team23Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team23Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team24Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team24Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team24Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team24Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team25Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team25Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team25Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team25Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team26Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team26Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team26Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team26Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team27Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team27Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team27Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team27Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team28Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team28Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team28Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team28Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team29Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team29Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team29Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team29Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team30Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team30Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team30Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team30Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team31Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team31Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team31Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team31Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team32Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team32Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team32Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team32Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LoserTable1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoserTable1 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''LosersName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LosersName As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TimePeriod1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TimePeriod1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''LosingPick1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LosingPick1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
