'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Season_End

    '''<summary>
    '''Contenders4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Contenders4 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''ContendersName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContendersName As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team1Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team1Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team1Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team1Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team2Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team2Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team2Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team2Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team3Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team3Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team3Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team3Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team4Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team4Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team4Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team4Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team5Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team5Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team5Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team5Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team6Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team6Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team6Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team6Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team7Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team7Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team7Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team7Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team8Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team8Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team8Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team8Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team9Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team9Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team9Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team9Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team10Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team10Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team10Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team10Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team11Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team11Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team11Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team11Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team12Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team12Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team12Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team12Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team13Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team13Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team13Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team13Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team14Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team14Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team14Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team14Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team15Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team15Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team15Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team15Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team16Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team16Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team16Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team16Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team17Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team17Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team17Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team17Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team18Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team18Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team18Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team18Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team19Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team19Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team19Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team19Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team20Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team20Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team20Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team20Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team21Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team21Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team21Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team21Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team22Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team22Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team22Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team22Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team23Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team23Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team23Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team23Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team24Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team24Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team24Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team24Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team25Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team25Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team25Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team25Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team26Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team26Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team26Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team26Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team27Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team27Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team27Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team27Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team28Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team28Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team28Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team28Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team29Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team29Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team29Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team29Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team30Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team30Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team30Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team30Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team31Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team31Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team31Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team31Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team32Label control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team32Label As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team32Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team32Label2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ContendersName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContendersName1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team1Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team1Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team1Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team1Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team2Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team2Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team2Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team2Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team3Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team3Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team3Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team3Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team4Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team4Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team4Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team4Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team5Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team5Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team5Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team5Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team6Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team6Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team6Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team6Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team7Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team7Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team7Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team7Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team8Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team8Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team8Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team8Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team9Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team9Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team9Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team9Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team10Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team10Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team10Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team10Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team11Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team11Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team11Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team11Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team12Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team12Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team12Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team12Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team13Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team13Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team13Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team13Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team14Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team14Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team14Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team14Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team15Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team15Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team15Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team15Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team16Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team16Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team16Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team16Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team17Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team17Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team17Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team17Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team18Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team18Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team18Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team18Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team19Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team19Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team19Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team19Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team20Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team20Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team20Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team20Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team21Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team21Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team21Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team21Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team22Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team22Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team22Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team22Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team23Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team23Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team23Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team23Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team24Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team24Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team24Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team24Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team25Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team25Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team25Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team25Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team26Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team26Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team26Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team26Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team27Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team27Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team27Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team27Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team28Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team28Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team28Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team28Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team29Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team29Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team29Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team29Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team30Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team30Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team30Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team30Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team31Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team31Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team31Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team31Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Team32Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team32Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Team32Icon2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Team32Icon2 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LoserTable1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoserTable1 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''LosersName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LosersName As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TimePeriod1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TimePeriod1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''LosingPick1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LosingPick1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
