'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Season_End

    '''<summary>
    '''Contenders2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Contenders2 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''ContendersName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContendersName As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''WashingtonImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WashingtonImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''WashingtonImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WashingtonImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''MiamiImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MiamiImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''MiamiImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MiamiImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ColoradoImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ColoradoImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''ColoradoImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ColoradoImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ArizonaImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ArizonaImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''ArizonaImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ArizonaImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''SanFranciscoImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SanFranciscoImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''SanFranciscoImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SanFranciscoImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''SanDiegoImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SanDiegoImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''SanDiegoImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SanDiegoImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''PittsburgImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PittsburgImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''PittsburgImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PittsburgImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''CincinnatiImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CincinnatiImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''CincinnatiImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CincinnatiImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''TorontoImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TorontoImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TorontoImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TorontoImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''NYYankeesImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NYYankeesImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''NYYankeesImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NYYankeesImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''BostonImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BostonImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''BostonImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BostonImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''TampaBayImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TampaBayImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TampaBayImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TampaBayImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AtlantaImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AtlantaImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AtlantaImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AtlantaImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''PhiladelphiaImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhiladelphiaImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''PhiladelphiaImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhiladelphiaImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ChicagoWhiteSoxImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChicagoWhiteSoxImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''ChicagoWhiteSoxImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChicagoWhiteSoxImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''DetroitImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DetroitImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''DetroitImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DetroitImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''KansasCityImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KansasCityImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''KansasCityImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KansasCityImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ClevelandImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClevelandImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''ClevelandImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClevelandImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''MilwaukeeImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MilwaukeeImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''MilwaukeeImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MilwaukeeImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LADodgersImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LADodgersImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''LADodgersImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LADodgersImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''MinnesotaImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MinnesotaImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''MinnesotaImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MinnesotaImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''OaklandImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OaklandImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''OaklandImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OaklandImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HoustonImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HoustonImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HoustonImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HoustonImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''TexasImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TexasImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TexasImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TexasImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''STLouisImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents STLouisImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''STLouisImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents STLouisImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ChicagoCubsImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChicagoCubsImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''ChicagoCubsImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChicagoCubsImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LAAngelsImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LAAngelsImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''LAAngelsImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LAAngelsImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''SeattleImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SeattleImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''SeattleImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SeattleImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''NYMetsImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NYMetsImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''NYMetsImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NYMetsImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''BaltimoreImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BaltimoreImage As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''BaltimoreImage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BaltimoreImage1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ContendersName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContendersName1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''WashingtonIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WashingtonIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''WashingtonIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WashingtonIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''MiamiIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MiamiIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''MiamiIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MiamiIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ColoradoIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ColoradoIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''ColoradoIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ColoradoIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ArizonaIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ArizonaIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''ArizonaIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ArizonaIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''SanFranciscoIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SanFranciscoIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''SanFranciscoIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SanFranciscoIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''SanDiegoIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SanDiegoIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''SanDiegoIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SanDiegoIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''PittsburgIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PittsburgIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''PittsburgIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PittsburgIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''CincinnatiIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CincinnatiIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''CincinnatiIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CincinnatiIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''TorontoIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TorontoIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TorontoIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TorontoIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''NYYankeesIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NYYankeesIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''NYYankeesIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NYYankeesIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''BostonIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BostonIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''BostonIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BostonIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''TampaBayIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TampaBayIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TampaBayIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TampaBayIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AtlantaIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AtlantaIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AtlantaIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AtlantaIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''PhiladelphiaIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhiladelphiaIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''PhiladelphiaIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PhiladelphiaIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ChicagoWhiteSoxIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChicagoWhiteSoxIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''ChicagoWhiteSoxIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChicagoWhiteSoxIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''DetroitIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DetroitIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''DetroitIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DetroitIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''KansasCityIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KansasCityIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''KansasCityIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KansasCityIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ClevelandIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClevelandIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''ClevelandIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClevelandIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''MilwaukeeIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MilwaukeeIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''MilwaukeeIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MilwaukeeIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LADodgersIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LADodgersIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''LADodgersIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LADodgersIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''MinnesotaIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MinnesotaIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''MinnesotaIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MinnesotaIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''OaklandIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OaklandIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''OaklandIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OaklandIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HoustonIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HoustonIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HoustonIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HoustonIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''TexasIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TexasIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''TexasIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TexasIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''STLouisIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents STLouisIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''STLouisIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents STLouisIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ChicagoCubsIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChicagoCubsIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''ChicagoCubsIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChicagoCubsIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LAAngelsIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LAAngelsIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''LAAngelsIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LAAngelsIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''SeattleIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SeattleIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''SeattleIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SeattleIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''NYMetsIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NYMetsIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''NYMetsIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NYMetsIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''BaltimoreIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BaltimoreIcon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''BaltimoreIcon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BaltimoreIcon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''LoserTable1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoserTable1 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''LosersName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LosersName As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''DayId1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DayId1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''LosingPick1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LosingPick1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
