'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WeeklyScoringUpdate

    '''<summary>
    '''TeamsByGameTable1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TeamsByGameTable1 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''Nothing1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber3 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber4 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber5 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber6 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber7 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber8 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber9 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber10 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber11 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber12 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber13 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber14 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber15 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber16 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Status1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Status1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber1Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber1Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber2Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber2Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber3Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber3Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber4Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber4Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber5Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber5Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber6Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber6Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber7Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber7Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber8Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber8Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber9Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber9Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber10Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber10Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber11Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber11Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber12Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber12Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber13Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber13Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber14Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber14Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber15Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber15Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber16Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber16Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''Nothing1A control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing1A As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam1Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam1Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam1Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam1Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam1Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam1Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam1Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam1Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam2Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam2Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam2Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam2Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam2Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam2Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam2Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam2Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam3Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam3Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam3Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam3Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam3Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam3Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam3Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam3Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam4Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam4Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam4Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam4Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam4Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam4Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam4Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam4Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam5Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam5Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam5Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam5Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam5Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam5Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam5Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam5Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam6Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam6Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam6Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam6Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam6Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam6Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam6Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam6Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam7Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam7Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam7Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam7Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam7Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam7Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam7Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam7Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam8Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam8Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam8Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam8Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam8Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam8Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam8Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam8Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam9Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam9Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam9Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam9Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam9Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam9Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam9Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam9Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam10Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam10Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam10Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam10Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam10Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam10Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam10Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam10Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam11Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam11Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam11Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam11Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam11Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam11Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam11Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam11Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam12Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam12Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam12Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam12Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam12Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam12Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam12Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam12Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam13Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam13Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam13Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam13Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam13Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam13Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam13Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam13Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam14Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam14Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam14Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam14Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam14Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam14Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam14Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam14Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam15Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam15Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam15Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam15Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam15Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam15Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam15Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam15Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam16Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam16Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam16Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam16Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam16Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam16Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam16Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam16Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Nothing1C control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing1C As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam1Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam1Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam1Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam1Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam1Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam1Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam1Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam1Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam2Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam2Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam2Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam2Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam2Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam2Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam2Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam2Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam3Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam3Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam3Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam3Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam3Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam3Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam3Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam3Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam4Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam4Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam4Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam4Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam4Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam4Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam4Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam4Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam5Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam5Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam5Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam5Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam5Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam5Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam5Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam5Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam6Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam6Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam6Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam6Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam6Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam6Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam6Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam6Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam7Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam7Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam7Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam7Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam7Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam7Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam7Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam7Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam8Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam8Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam8Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam8Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam8Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam8Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam8Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam8Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam9Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam9Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam9Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam9Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam9Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam9Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam9Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam9Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam10Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam10Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam10Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam10Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam10Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam10Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam10Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam10Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam11Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam11Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam11Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam11Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam11Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam11Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam11Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam11Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam12Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam12Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam12Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam12Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam12Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam12Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam12Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam12Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam13Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam13Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam13Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam13Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam13Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam13Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam13Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam13Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam14Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam14Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam14Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam14Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam14Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam14Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam14Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam14Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam15Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam15Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam15Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam15Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam15Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam15Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam15Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam15Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam16Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam16Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam16Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam16Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam16Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam16Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam16Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam16Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Nothing1B control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nothing1B As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore1 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore1 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore2 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore2 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore3 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore3 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore4 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore4 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore5 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore5 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore6 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore6 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore7 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore7 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore8 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore8 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore9 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore9 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore10 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore10 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore11 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore11 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore12 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore12 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore13 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore13 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore14 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore14 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore15 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore15 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''HomeScore16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeScore16 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''AwayScore16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayScore16 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
