'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WeeklyLoserPoolUserEntry

    '''<summary>
    '''loser1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loser1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''GameTable1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameTable1 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''GameNumber1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber1 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber2 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber3 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber4 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber1Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber1Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber2Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber2Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber3Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber3Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber4Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber4Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam1Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam1Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam1Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam1Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam1Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam1Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam1Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam1Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam2Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam2Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam2Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam2Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam2Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam2Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam2Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam2Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam3Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam3Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam3Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam3Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam3Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam3Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam3Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam3Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam4Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam4Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam4Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam4Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam4Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam4Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam4Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam4Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam1Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam1Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam1Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam1Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam1Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam1Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam1Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam1Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam2Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam2Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam2Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam2Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam2Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam2Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam2Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam2Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam3Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam3Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam3Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam3Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam3Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam3Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam3Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam3Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam4Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam4Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam4Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam4Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam4Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam4Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam4Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam4Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomePick1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePick1 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game1HomeRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game1HomeRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Home1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home1 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''AwayPick1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPick1 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game1AwayRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game1AwayRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Away1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Away1 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''HomePick2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePick2 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game2HomeRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game2HomeRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Home2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home2 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''AwayPick2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPick2 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game2AwayRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game2AwayRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Away2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Away2 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''HomePick3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePick3 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game3HomeRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game3HomeRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Home3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home3 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''AwayPick3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPick3 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game3AwayRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game3AwayRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Away3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Away3 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''HomePick4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePick4 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game4HomeRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game4HomeRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Home4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home4 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''AwayPick4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPick4 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game4AwayRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game4AwayRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Away4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Away4 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''GameTable2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameTable2 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''GameNumber5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber5 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber6 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber7 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber8 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber5Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber5Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber6Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber6Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber7Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber7Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber8Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber8Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam5Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam5Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam5Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam5Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam5Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam5Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam5Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam5Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam6Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam6Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam6Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam6Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam6Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam6Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam6Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam6Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam7Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam7Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam7Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam7Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam7Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam7Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam7Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam7Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam8Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam8Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam8Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam8Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam8Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam8Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam8Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam8Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam5Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam5Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam5Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam5Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam5Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam5Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam5Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam5Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam6Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam6Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam6Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam6Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam6Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam6Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam6Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam6Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam7Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam7Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam7Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam7Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam7Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam7Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam7Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam7Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam8Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam8Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam8Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam8Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam8Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam8Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam8Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam8Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomePick5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePick5 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game5HomeRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game5HomeRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Home5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home5 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''AwayPick5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPick5 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game5AwayRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game5AwayRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Away5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Away5 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''HomePick6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePick6 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game6HomeRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game6HomeRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Home6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home6 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''AwayPick6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPick6 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game6AwayRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game6AwayRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Away6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Away6 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''HomePick7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePick7 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game7HomeRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game7HomeRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Home7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home7 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''AwayPick7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPick7 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game7AwayRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game7AwayRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Away7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Away7 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''HomePick8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePick8 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game8HomeRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game8HomeRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Home8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home8 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''AwayPick8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPick8 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game8AwayRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game8AwayRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Away8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Away8 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''GameTable3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameTable3 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''GameNumber9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber9 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber10 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber11 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber12 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber9Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber9Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber10Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber10Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber11Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber11Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber12Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber12Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam9Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam9Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam9Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam9Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam9Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam9Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam9Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam9Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam10Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam10Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam10Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam10Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam10Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam10Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam10Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam10Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam11Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam11Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam11Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam11Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam11Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam11Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam11Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam11Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam12Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam12Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam12Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam12Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam12Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam12Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam12Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam12Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam9Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam9Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam9Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam9Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam9Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam9Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam9Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam9Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam10Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam10Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam10Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam10Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam10Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam10Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam10Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam10Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam11Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam11Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam11Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam11Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam11Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam11Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam11Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam11Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam12Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam12Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam12Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam12Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam12Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam12Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam12Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam12Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomePick9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePick9 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game9HomeRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game9HomeRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Home9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home9 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''AwayPick9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPick9 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game9AwayRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game9AwayRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Away9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Away9 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''HomePick10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePick10 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game10HomeRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game10HomeRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Home10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home10 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''AwayPick10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPick10 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game10AwayRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game10AwayRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Away10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Away10 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''HomePick11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePick11 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game11HomeRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game11HomeRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Home11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home11 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''AwayPick11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPick11 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game11AwayRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game11AwayRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Away11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Away11 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''HomePick12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePick12 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game12HomeRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game12HomeRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Home12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home12 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''AwayPick12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPick12 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game12AwayRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game12AwayRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Away12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Away12 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''GameTable4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameTable4 As Global.System.Web.UI.WebControls.Table

    '''<summary>
    '''GameNumber13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber13 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber14 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber15 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber16 As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber13Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber13Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber14Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber14Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber15Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber15Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''GameNumber16Status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GameNumber16Status As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam13Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam13Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam13Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam13Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam13Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam13Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam13Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam13Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam14Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam14Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam14Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam14Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam14Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam14Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam14Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam14Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam15Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam15Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam15Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam15Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam15Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam15Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam15Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam15Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam16Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam16Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam16Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam16Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam16Image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam16Image As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam16Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam16Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam13Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam13Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam13Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam13Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam13Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam13Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam13Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam13Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam14Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam14Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam14Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam14Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam14Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam14Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam14Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam14Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam15Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam15Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam15Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam15Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam15Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam15Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam15Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam15Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomeTeam16Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam16Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''HomeTeam16Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomeTeam16Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''AwayTeam16Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam16Icon As Global.System.Web.UI.WebControls.TableHeaderCell

    '''<summary>
    '''AwayTeam16Icon1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayTeam16Icon1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''HomePick13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePick13 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game13HomeRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game13HomeRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Home13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home13 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''AwayPick13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPick13 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game13AwayRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game13AwayRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Away13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Away13 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''HomePick14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePick14 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game14HomeRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game14HomeRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Home14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home14 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''AwayPick14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPick14 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game14AwayRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game14AwayRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Away14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Away14 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''HomePick15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePick15 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game15HomeRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game15HomeRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Home15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home15 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''AwayPick15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPick15 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game15AwayRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game15AwayRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Away15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Away15 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''HomePick16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HomePick16 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game16HomeRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game16HomeRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Home16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Home16 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''AwayPick16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AwayPick16 As Global.System.Web.UI.WebControls.TableCell

    '''<summary>
    '''Game16AwayRadio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Game16AwayRadio As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''Away16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Away16 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button2 As Global.System.Web.UI.WebControls.Button
End Class
